services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"  # SMTP port (for sending emails to MailHog)
    restart: unless-stopped # Restart the container unless explicitly stopped
    container_name: mailhog
    networks:
      - smtp
      - proxy
networks:
  smtp:
    external: true
  proxy:
    external: true
