services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.3.4
    container_name: grafana
    ports:
      - "9091:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: docker.io/prom/prometheus:v3.2.1
    container_name: prometheus
    ports:
      - 9092:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - /home/eduardo/projects/bill-infra/prometheus/config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.51.0
    container_name: cadvisor
    ports:
      - 9093:8080
    volumes:
      - /:/rootfs:ro
      - /run:/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    devices:
      - /dev/kmsg
    privileged: true
    restart: unless-stopped

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.9.0
    container_name: node_exporter
    command: "--path.rootfs=/host"
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave

volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
