services:
  gitlab:
    image: gitlab/gitlab-ce:17.7.6-ce.0
    container_name: gitlab
    restart: always
    hostname: gitlab.azagal.duckdns.org
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.azagal.duckdns.org'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['redirect_http_to_https'] = false
        gitlab_rails['gitlab_shell_ssh_port'] = 22

        ## OpenID Connect Configuration
        gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
        gitlab_rails['omniauth_sync_email_from_provider'] = 'openid_connect'
        gitlab_rails['omniauth_sync_profile_from_provider'] = ['openid_connect']
        gitlab_rails['omniauth_sync_profile_attributes'] = ['email', 'name']
        # gitlab_rails['omniauth_auto_sign_in_with_provider'] = 'openid_connect'
        gitlab_rails['omniauth_block_auto_created_users'] = false
        gitlab_rails['omniauth_auto_link_saml_user'] = true
        gitlab_rails['omniauth_auto_link_user'] = ['openid_connect']
        gitlab_rails['omniauth_providers'] = [
          {
            name: 'openid_connect',
            label: 'Azagal OIDC Login',
            args: {
              name: 'openid_connect',
              scope: ['openid','profile','email'],
              response_type: 'code',
              issuer: 'https://authentik.azagal.duckdns.org/application/o/gitlab/',
              discovery: true,
              client_auth_method: 'query',
              uid_field: 'sub',
              send_scope_to_token_endpoint: 'true',
              pkce: true,
              client_options: {
                identifier: '${OIDC_CLIENT_ID}',
                secret: '${OIDC_CLIENT_SECRET}',
                redirect_uri: 'https://gitlab.azagal.duckdns.org/users/auth/openid_connect/callback'
              }
            }
          }
        ]
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = 'mailhog'
        gitlab_rails['smtp_port'] = 1025
        gitlab_rails['smtp_user_name'] = nil
        gitlab_rails['smtp_password'] = nil
        gitlab_rails['smtp_domain'] = 'azagal.duckdns.org'
        gitlab_rails['smtp_tls'] = false
        gitlab_rails['smtp_enable_starttls_auto'] = false
    ports:
      - "82:80"
      - "2222:22"
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: "256m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - gitlab_network
      - mailhog_network

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner
    restart: always
    depends_on:
      gitlab:
        condition: service_healthy
    volumes:
      - ./config/gitlab-runner:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_network

networks:
  mailhog_network:
    external: true
  gitlab_network:
    driver: bridge