services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    env_file:
      - .env
    command: tunnel --no-autoupdate run --token $TOKEN
    networks:
      - proxy
networks:
  proxy:
    external: true
